[project]
name = "comfyui-datadog-monitor"
description = ""
version = "1.0.5"
license = {file = "LICENSE"}
dependencies = [
    "ddtrace>=4.0.0",
]

[project.urls]
Repository = "https://github.com/Comfy-Org/comfyui-datadog-monitor"
#  Used by Comfy Registry https://registry.comfy.org

[tool.comfy]
PublisherId = "Comfy-Org"
DisplayName = "comfyui-datadog-monitor"
Icon = ""
includes = []
